name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  unix:
    runs-on: "ubuntu-latest"
    name: "ubuntu"
    env:
      CCACHE_BASEDIR: "${{ github.workspace }}"
      CCACHE_DIR: "${{ github.workspace }}/.ccache"
      CCACHE_COMPRESS: true
      CCACHE_COMPRESSLEVEL: 6
      CCACHE_MAXSIZE: 400M

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      name: "Prepare base dependencies"
      with:
        python-version: "3.8"
        activate-environment: build
        environment-file: devtools/ci/gh-actions/conda-envs/build.yml
        auto-activate-base: false

    - name: "Install martini_openmm"
      shell: bash -l {0}
      run: python setup.py install

#    - name: "Download and untar gromacs"
#      run: |
#        wget https://ftp.gromacs.org/gromacs/gromacs-2021.2.tar.gz
#        tar zxf gromacs-2021.2.tar.gz

#    - name: "Build and install gromacs"
#      working-directory: ./gromacs-2021.2
#      run: |
#        mkdir build
#        cd build
#        cmake .. -DGMX_BUILD_OWN_FFTW=ON -DGMX_DOUBLE=on
#        make
#        sudo make install

    - name: "Run tests"
      shell: bash -l {0}
      run: |
        #source /usr/local/gromacs/bin/GMXRC
        pwd
        ls -lh
        pytest




